version: '3.9'
services:
  database:
    image: postgres:15.3
    container_name: springessentials
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=anime"
    ports:
      - "5441:5432"
    volumes:
      - devdojo_data:/var/lib/mysql
volumes:
  devdojo_data: